# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
Ingredient.create([
  { name_hiragana: "あじ", name_katakana: "アジ", name_kanji: "鯵", display_name: "鯵" },
  { name_hiragana: "いんげん", name_katakana: "インゲン", name_kanji: "隠元", display_name: "隠元" },
  { name_hiragana: "うど", name_katakana: "ウド", name_kanji: "独活", display_name: "独活" },
  { name_hiragana: "えんどう", name_katakana: "エンドウ", name_kanji: "豌豆", display_name: "豌豆" },
  { name_hiragana: "おくら", name_katakana: "オクラ", name_kanji: "秋葵", display_name: "秋葵" },
  { name_hiragana: "かぼちゃ", name_katakana: "カボチャ", name_kanji: "南瓜", display_name: "南瓜" },
  { name_hiragana: "きゅうり", name_katakana: "キュウリ", name_kanji: "胡瓜", display_name: "胡瓜" },
  { name_hiragana: "くり", name_katakana: "クリ", name_kanji: "栗", display_name: "栗" },
  { name_hiragana: "けんちんじる", name_katakana: "ケンチンジル", name_kanji: "建長汁", display_name: "建長汁" },
  { name_hiragana: "こまつな", name_katakana: "コマツナ", name_kanji: "小松菜", display_name: "小松菜" },
  { name_hiragana: "さけ", name_katakana: "サケ", name_kanji: "鮭", display_name: "鮭" },
  { name_hiragana: "しいたけ", name_katakana: "シイタケ", name_kanji: "椎茸", display_name: "椎茸" },
  { name_hiragana: "すずき", name_katakana: "スズキ", name_kanji: "鱸", display_name: "鱸" },
  { name_hiragana: "せり", name_katakana: "セリ", name_kanji: "芹", display_name: "芹" },
  { name_hiragana: "たまねぎ", name_katakana: "タマネギ", name_kanji: "玉葱", display_name: "玉葱" },
  { name_hiragana: "ちくわ", name_katakana: "チクワ", name_kanji: "竹輪", display_name: "竹輪" },
  { name_hiragana: "つくね", name_katakana: "ツクネ", name_kanji: "捏", display_name: "捏" },
  { name_hiragana: "とまと", name_katakana: "トマト", name_kanji: "蕃茄", display_name: "蕃茄" },
  { name_hiragana: "なす", name_katakana: "ナス", name_kanji: "茄子", display_name: "茄子" },
  { name_hiragana: "にんじん", name_katakana: "ニンジン", name_kanji: "人参", display_name: "人参" },
  { name_hiragana: "はくさい", name_katakana: "ハクサイ", name_kanji: "白菜", display_name: "白菜" },
  { name_hiragana: "ひじき", name_katakana: "ヒジキ", name_kanji: "鹿尾菜", display_name: "鹿尾菜" },
  { name_hiragana: "ふき", name_katakana: "フキ", name_kanji: "蕗", display_name: "蕗" },
  { name_hiragana: "ほうれんそう", name_katakana: "ホウレンソウ", name_kanji: "法蓮草", display_name: "法蓮草" },
  { name_hiragana: "まいたけ", name_katakana: "マイタケ", name_kanji: "舞茸", display_name: "舞茸" },
  { name_hiragana: "みかん", name_katakana: "ミカン", name_kanji: "蜜柑", display_name: "蜜柑" },
  { name_hiragana: "やまいも", name_katakana: "ヤマイモ", name_kanji: "山芋", display_name: "山芋" },
  { name_hiragana: "ゆず", name_katakana: "ユズ", name_kanji: "柚子", display_name: "柚子" },
  { name_hiragana: "らっきょう", name_katakana: "ラッキョウ", name_kanji: "薤", display_name: "薤" },
  { name_hiragana: "わかめ", name_katakana: "ワカメ", name_kanji: "若布", display_name: "若布" },
  { name_hiragana: "あさり", name_katakana: "アサリ", name_kanji: "浅蜊", display_name: "アサリ" },
  { name_hiragana: "いか", name_katakana: "イカ", name_kanji: "烏賊", display_name: "イカ" },
  { name_hiragana: "いくら", name_katakana: "イクラ", name_kanji: "筋子", display_name: "イクラ" },
  { name_hiragana: "いしもち", name_katakana: "イシモチ", name_kanji: "石持", display_name: "イシモチ" },
  { name_hiragana: "いちご", name_katakana: "イチゴ", name_kanji: "苺", display_name: "イチゴ" },
  { name_hiragana: "いわし", name_katakana: "イワシ", name_kanji: "鰯", display_name: "イワシ" },
  { name_hiragana: "うなぎ", name_katakana: "ウナギ", name_kanji: "鰻", display_name: "ウナギ" },
  { name_hiragana: "えび", name_katakana: "エビ", name_kanji: "海老", display_name: "エビ" },
  { name_hiragana: "おろし", name_katakana: "オロシ", name_kanji: "卸", display_name: "オロシ" },
  { name_hiragana: "かつお", name_katakana: "カツオ", name_kanji: "鰹", display_name: "カツオ" },
  { name_hiragana: "かに", name_katakana: "カニ", name_kanji: "蟹", display_name: "カニ" },
  { name_hiragana: "かまぼこ", name_katakana: "カマボコ", name_kanji: "蒲鉾", display_name: "カマボコ" },
  { name_hiragana: "からし", name_katakana: "カラシ", name_kanji: "芥子", display_name: "カラシ" },
  { name_hiragana: "きび", name_katakana: "キビ", name_kanji: "黍", display_name: "キビ" },
  { name_hiragana: "ぎんなん", name_katakana: "ギンナン", name_kanji: "銀杏", display_name: "ギンナン" },
  { name_hiragana: "くわい", name_katakana: "クワイ", name_kanji: "慈姑", display_name: "クワイ" },
  { name_hiragana: "ごぼう", name_katakana: "ゴボウ", name_kanji: "牛蒡", display_name: "ゴボウ" },
  { name_hiragana: "さば", name_katakana: "サバ", name_kanji: "鯖", display_name: "サバ" },
  { name_hiragana: "さわら", name_katakana: "サワラ", name_kanji: "鰆", display_name: "サワラ" },
  { name_hiragana: "しめじ", name_katakana: "シメジ", name_kanji: "占地", display_name: "シメジ" },
  { name_hiragana: "じゃがいも", name_katakana: "ジャガイモ", name_kanji: "馬鈴薯", display_name: "ジャガイモ" },
  { name_hiragana: "すいか", name_katakana: "スイカ", name_kanji: "西瓜", display_name: "スイカ" },
  { name_hiragana: "たこ", name_katakana: "タコ", name_kanji: "蛸", display_name: "タコ" },
  { name_hiragana: "たら", name_katakana: "タラ", name_kanji: "鱈", display_name: "タラ" },
  { name_hiragana: "だいこん", name_katakana: "ダイコン", name_kanji: "大根", display_name: "ダイコン" },
  { name_hiragana: "ちんげんさい", name_katakana: "チンゲンサイ", name_kanji: "青梗菜", display_name: "チンゲンサイ" },
  { name_hiragana: "つばめのす", name_katakana: "ツバメノス", name_kanji: "燕巣", display_name: "ツバメノス" },
  { name_hiragana: "とりにく", name_katakana: "トリニク", name_kanji: "鶏肉", display_name: "トリニク" },
  { name_hiragana: "なまこ", name_katakana: "ナマコ", name_kanji: "海鼠", display_name: "ナマコ" },
  { name_hiragana: "にんにく", name_katakana: "ニンニク", name_kanji: "蒜", display_name: "ニンニク" },
  { name_hiragana: "はまち", name_katakana: "ハマチ", name_kanji: "鰤", display_name: "ハマチ" },
  { name_hiragana: "びわ", name_katakana: "ビワ", name_kanji: "枇杷", display_name: "ビワ" },
  { name_hiragana: "ぶどう", name_katakana: "ブドウ", name_kanji: "葡萄", display_name: "ブドウ" },
  { name_hiragana: "ほたて", name_katakana: "ホタテ", name_kanji: "帆立", display_name: "ホタテ" },
  { name_hiragana: "まぐろ", name_katakana: "マグロ", name_kanji: "鮪", display_name: "マグロ" },
  { name_hiragana: "もずく", name_katakana: "モズク", name_kanji: "藻付", display_name: "モズク" },
  { name_hiragana: "やりいか", name_katakana: "ヤリイカ", name_kanji: "槍烏賊", display_name: "ヤリイカ" },
  { name_hiragana: "ゆりね", name_katakana: "ユリネ", name_kanji: "百合根", display_name: "ユリネ" },
  { name_hiragana: "れんこん", name_katakana: "レンコン", name_kanji: "蓮根", display_name: "レンコン" },
  { name_hiragana: "ろーす", name_katakana: "ロース", name_kanji: "露西", display_name: "ロース" }
])
